# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/126F0Bxdkyd9dQQvebAKCvG1LqZEla4U1
"""

#the function works based on user input, we put our portfolio lower
import mod
preturn()

#for TSLA, UL, AMZN, GOOG, MSFT
#weights are 0.2, 0.2, 0.2, 0.2, 0.2
#Annual return on portfolio: in % 28.676717603664297